spring:
  application:
    name: basic-jpa

  datasource:
    hikari:
      mysql :
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false&&allowMultiQueries=true&rewriteBatchedStatements=true
        username: ENC[Fu9sG8qRC8kIweIS4Lhk2G69ZWTqXt+GyAhdzAorwE7uwXk2iUEfOqZtdnKcp/4+]
        password: ENC[8Kywn+mJcRbX7CFBlRnUsJes74ycM/3VDezaCd4elPruJK99yYwJvF9FC+ZSeLSE]
        pool-name: MYSQL_DB
        idle-timeout: 10000 # 기본값 600000 (10분)
        connection-timeout: 30000 # 기본값 30000 (30초)
        minimum-idle: 5 # 기본값 maximum-pool-size와 같음
        maximum-pool-size: 10 # 기본값 10
        max-lifetime: 1800000 # 기본값 1800000 (30분)
      postgresql:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/test
        username: ENC[Fu9sG8qRC8kIweIS4Lhk2G69ZWTqXt+GyAhdzAorwE7uwXk2iUEfOqZtdnKcp/4+]
        password: ENC[8Kywn+mJcRbX7CFBlRnUsJes74ycM/3VDezaCd4elPruJK99yYwJvF9FC+ZSeLSE]
        pool-name: POSTGRESQL_DB
        idle-timeout: 10000 # 기본값 600000 (10분)
        connection-timeout: 30000 # 기본값 30000 (30초)
        minimum-idle: 5 # 기본값 maximum-pool-size와 같음
        maximum-pool-size: 10 # 기본값 10
        max-lifetime: 1800000 # 기본값 1800000 (30분)

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 16
        id.new_generator_mappings: true
        format_sql: false
        show_sql: false
        use_sql_comments: false
    hibernate:
      ddl-auto: validate

  devtools:
    restart.enabled: false
    livereload.enabled: true

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 1000
    pool-size: 1
    provider-name: SunJCE
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64
    property:
      prefix: 'ENC['
      suffix: ']'

logging:
  level:
    io.devfactory: debug

    # jps 기본 로그 설정 (show-sql 옵션은 권장하지 않음)
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true

sql:
  init:
    mysql:
      locations:
        - sql/schema-mysql.sql
        - sql/data-mysql.sql
    postgresql:
      locations:
        - sql/schema-postgresql.sql
        - sql/data-postgresql.sql
