spring:
  application:
    name: basic-jpa

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: 1234

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username: test
#    password: 1234

  sql:
    init:
      mode: always
      platform: postgresql
#      platform: mysql
      schema-locations: classpath:sql/schema-${spring.sql.init.platform}.sql
      data-locations: classpath:sql/data-${spring.sql.init.platform}.sql

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  devtools:
    restart.enabled: false
    livereload.enabled: true

logging:
  level:
    io.devfactory: debug
    org.hibernate.SQL: debug
    #org.springframework: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
